language: android
os: linux
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - android-19
addons:
  chrome: stable
before_install:
  - nvm install 12
  - npm install -g ionic cordova
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run e2e
before_deploy:
  - npm run sync
deploy:
  cleanup: false
  provider: script
  on:
    branch: master
  script: bash deploy.sh
  edge: true
