language: node_js
node_js:
  - "12.11.0"

branches:
  only:
    - master

before_script:
  - npm install -g ionic cordova
  - ionic cordova platform add browser

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - ionic build --prod

before_deploy:
  - npm install -g replace
  - replace 'href="/"' 'href="/'$GITHUB_PAGE_SUBDIRECTORY'"' www/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: www

