language: android
os: linux
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - android-19
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get -y install google-chrome-stable
  - nvm install 12
  - npm install -g ionic cordova
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run e2e
before_deploy:
  - npm run sync
deploy:
  cleanup: false
  provider: script
  on:
    branch: master
  script: bash deploy.sh
  edge: true

