language: android
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-23
  - extra
  - add-on
licenses:
  - android-sdk-preview-license-.+
  - google-gdk-license-.+
  - android-sdk-license-.+
addons:
  chrome: stable
before_install:
  - nvm install 12
  - npm install -g ionic cordova
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run e2e
before_deploy:
  - npm run sync
  - ionic cordova platform add browser
  - ionic build --prod
  - npm install -g replace
  - replace 'href="/"' 'href="/'$GITHUB_PAGE_SUBDIRECTORY'"' www/index.html
  - ionic cordova platform add android
  - yes | sdkmanager "build-tools;28.0.3"
  - openssl aes-256-cbc -K $encrypted_c11b1b4317aa_key -iv $encrypted_c11b1b4317aa_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - rvm install 2.6.5
  - gem install fastlane
  - gem install supply
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
    local_dir: www
  - provider: script
    on:
      branch: master
    script:
      - ionic cordova build --release --prod android
      - jarsigner -verbose -sigalg SHA1withRSA -storepass $STOREPASS -keypass $KEYPASS -digestalg SHA1 -keystore android.jks platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk android_criptoarbitragem
      - /usr/local/android-sdk/build-tools/28.0.3/zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk app.apk
      - fastlane supply -v
      - fastlane supply run -j google-console-api.json -p br.com.criptoarbitragem -b app.apk -e $RELEASE_STATUS

