language: node
os: linux
addons:
  chrome: stable
before_install:
  - nvm install 12 > /dev/null
  - npm install -g ionic cordova > /dev/null
  - npm install > /dev/null
script:
  - npm run lint > /dev/null
  - npm run test > /dev/null
before_deploy:
  - npm run sync > /dev/null
deploy:
  cleanup: false
  provider: script
  on:
    branch: master
  script: bash deploy.sh
  edge: true
